In [1]:
import polars as pl

# Q1

## prep

In [4]:
urls = {
    'airports':'https://sacodeassessment.blob.core.windows.net/public/airports.csv'
    , 'countries': 'https://sacodeassessment.blob.core.windows.net/public/countries.csv'
    , 'runways': 'https://sacodeassessment.blob.core.windows.net/public/runways.csv'
}

In [5]:
airports = pl.read_csv(urls['airports'])
countries = pl.read_csv(urls['countries'])
runways = pl.read_csv(urls['runways'],infer_schema_length=10000)

In [6]:
airports.head()

shape: (5, 18)
┌────────┬───────┬─────────────┬─────────────┬───┬────────────┬───────────┬─────────────┬──────────┐
│ id     ┆ ident ┆ type        ┆ name        ┆ … ┆ local_code ┆ home_link ┆ wikipedia_l ┆ keywords │
│ ---    ┆ ---   ┆ ---         ┆ ---         ┆   ┆ ---        ┆ ---       ┆ ink         ┆ ---      │
│ i64    ┆ str   ┆ str         ┆ str         ┆   ┆ str        ┆ str       ┆ ---         ┆ str      │
│        ┆       ┆             ┆             ┆   ┆            ┆           ┆ str         ┆          │
╞════════╪═══════╪═════════════╪═════════════╪═══╪════════════╪═══════════╪═════════════╪══════════╡
│ 6523   ┆ 00A   ┆ heliport    ┆ Total Rf    ┆ … ┆ 00A        ┆ null      ┆ null        ┆ null     │
│        ┆       ┆             ┆ Heliport    ┆   ┆            ┆           ┆             ┆          │
│ 323361 ┆ 00AA  ┆ small_airpo ┆ Aero B      ┆ … ┆ 00AA       ┆ null      ┆ null        ┆ null     │
│        ┆       ┆ rt          ┆ Ranch       ┆   ┆            ┆           ┆             ┆          │
│        ┆       ┆             ┆ Airport     ┆   ┆            ┆           ┆             ┆          │
│ 6524   ┆ 00AK  ┆ small_airpo ┆ Lowell      ┆ … ┆ 00AK       ┆ null      ┆ null        ┆ null     │
│        ┆       ┆ rt          ┆ Field       ┆   ┆            ┆           ┆             ┆          │
│ 6525   ┆ 00AL  ┆ small_airpo ┆ Epps        ┆ … ┆ 00AL       ┆ null      ┆ null        ┆ null     │
│        ┆       ┆ rt          ┆ Airpark     ┆   ┆            ┆           ┆             ┆          │
│ 6526   ┆ 00AR  ┆ closed      ┆ Newport     ┆ … ┆ null       ┆ null      ┆ null        ┆ 00AR     │
│        ┆       ┆             ┆ Hospital &  ┆   ┆            ┆           ┆             ┆          │
│        ┆       ┆             ┆ Clinic      ┆   ┆            ┆           ┆             ┆          │
│        ┆       ┆             ┆ Helipo…     ┆   ┆            ┆           ┆             ┆          │
└────────┴───────┴─────────────┴─────────────┴───┴────────────┴───────────┴─────────────┴──────────┘

In [7]:
countries.head()

shape: (5, 6)
┌────────┬──────┬──────────────────────┬───────────┬───────────────────────┬───────────────────────┐
│ id     ┆ code ┆ name                 ┆ continent ┆ wikipedia_link        ┆ keywords              │
│ ---    ┆ ---  ┆ ---                  ┆ ---       ┆ ---                   ┆ ---                   │
│ i64    ┆ str  ┆ str                  ┆ str       ┆ str                   ┆ str                   │
╞════════╪══════╪══════════════════════╪═══════════╪═══════════════════════╪═══════════════════════╡
│ 302672 ┆ AD   ┆ Andorra              ┆ EU        ┆ https://en.wikipedia. ┆ null                  │
│        ┆      ┆                      ┆           ┆ org/wiki/An…          ┆                       │
│ 302618 ┆ AE   ┆ United Arab Emirates ┆ AS        ┆ https://en.wikipedia. ┆ UAE,مطارات في         │
│        ┆      ┆                      ┆           ┆ org/wiki/Un…          ┆ الإمارات العربية ا…   │
│ 302619 ┆ AF   ┆ Afghanistan          ┆ AS        ┆ https://en.wikipedia. ┆ null                  │
│        ┆      ┆                      ┆           ┆ org/wiki/Af…          ┆                       │
│ 302722 ┆ AG   ┆ Antigua and Barbuda  ┆ NA        ┆ https://en.wikipedia. ┆ null                  │
│        ┆      ┆                      ┆           ┆ org/wiki/An…          ┆                       │
│ 302723 ┆ AI   ┆ Anguilla             ┆ NA        ┆ https://en.wikipedia. ┆ null                  │
│        ┆      ┆                      ┆           ┆ org/wiki/An…          ┆                       │
└────────┴──────┴──────────────────────┴───────────┴───────────────────────┴───────────────────────┘

In [8]:
runways.head()

shape: (5, 20)
┌────────┬────────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ id     ┆ airport_re ┆ airport_id ┆ length_ft ┆ … ┆ he_longit ┆ he_elevat ┆ he_headin ┆ he_displa │
│ ---    ┆ f          ┆ ent        ┆ ---       ┆   ┆ ude_deg   ┆ ion_ft    ┆ g_degT    ┆ ced_thres │
│ i64    ┆ ---        ┆ ---        ┆ i64       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ hold_ft   │
│        ┆ i64        ┆ str        ┆           ┆   ┆ f64       ┆ i64       ┆ f64       ┆ ---       │
│        ┆            ┆            ┆           ┆   ┆           ┆           ┆           ┆ i64       │
╞════════╪════════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 269408 ┆ 6523       ┆ 00A        ┆ 80        ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 255155 ┆ 6524       ┆ 00AK       ┆ 2500      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 254165 ┆ 6525       ┆ 00AL       ┆ 2300      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 270932 ┆ 6526       ┆ 00AR       ┆ 40        ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 322128 ┆ 322127     ┆ 00AS       ┆ 1450      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
└────────┴────────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [10]:
airports.describe()

shape: (9, 19)
┌────────────┬────────────┬───────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ statistic  ┆ id         ┆ ident ┆ type       ┆ … ┆ local_cod ┆ home_link ┆ wikipedia ┆ keywords  │
│ ---        ┆ ---        ┆ ---   ┆ ---        ┆   ┆ e         ┆ ---       ┆ _link     ┆ ---       │
│ str        ┆ f64        ┆ str   ┆ str        ┆   ┆ ---       ┆ str       ┆ ---       ┆ str       │
│            ┆            ┆       ┆            ┆   ┆ str       ┆           ┆ str       ┆           │
╞════════════╪════════════╪═══════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ count      ┆ 63253.0    ┆ 63253 ┆ 63253      ┆ … ┆ 31246     ┆ 3242      ┆ 10274     ┆ 11489     │
│ null_count ┆ 0.0        ┆ 0     ┆ 0          ┆ … ┆ 32007     ┆ 60011     ┆ 52979     ┆ 51764     │
│ mean       ┆ 116589.540 ┆ null  ┆ null       ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│            ┆ 828        ┆       ┆            ┆   ┆           ┆           ┆           ┆           │
│ std        ┆ 141141.632 ┆ null  ┆ null       ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│            ┆ 232        ┆       ┆            ┆   ┆           ┆           ┆           ┆           │
│ min        ┆ 2.0        ┆ 00A   ┆ balloonpor ┆ … ┆ -         ┆ http://81 ┆ http://de ┆ "El       │
│            ┆            ┆       ┆ t          ┆   ┆           ┆ 3.mnd.gov ┆ .wikipedi ┆ Ciprés"   │
│            ┆            ┆       ┆            ┆   ┆           ┆ .tw/engli ┆ a.org/wik ┆ Military  │
│            ┆            ┆       ┆            ┆   ┆           ┆ sh/       ┆ i/Alb…    ┆ Airbase   │
│            ┆            ┆       ┆            ┆   ┆           ┆           ┆           ┆ Num…      │
│ 25%        ┆ 15946.0    ┆ null  ┆ null       ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 50%        ┆ 32036.0    ┆ null  ┆ null       ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 75%        ┆ 317302.0   ┆ null  ┆ null       ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ max        ┆ 342279.0   ┆ spgl  ┆ small_airp ┆ … ┆ ZZV       ┆ https://y ┆ https://z ┆ 황수원비  │
│            ┆            ┆       ┆ ort        ┆   ┆           ┆ yb.ca/    ┆ h.wikiped ┆ 행장, 黃  │
│            ┆            ┆       ┆            ┆   ┆           ┆           ┆ ia.org/wi ┆ 水院飛行  │
│            ┆            ┆       ┆            ┆   ┆           ┆           ┆ ki/%E…    ┆ 場        │
└────────────┴────────────┴───────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [11]:
airports.select(
    pl.all().n_unique()
)

shape: (1, 18)
┌───────┬───────┬──────┬───────┬───┬────────────┬───────────┬────────────────┬──────────┐
│ id    ┆ ident ┆ type ┆ name  ┆ … ┆ local_code ┆ home_link ┆ wikipedia_link ┆ keywords │
│ ---   ┆ ---   ┆ ---  ┆ ---   ┆   ┆ ---        ┆ ---       ┆ ---            ┆ ---      │
│ u32   ┆ u32   ┆ u32  ┆ u32   ┆   ┆ u32        ┆ u32       ┆ u32            ┆ u32      │
╞═══════╪═══════╪══════╪═══════╪═══╪════════════╪═══════════╪════════════════╪══════════╡
│ 63253 ┆ 63253 ┆ 7    ┆ 60023 ┆ … ┆ 29700      ┆ 3228      ┆ 10202          ┆ 11207    │
└───────┴───────┴──────┴───────┴───┴────────────┴───────────┴────────────────┴──────────┘

In [12]:
countries.describe()

shape: (9, 7)
┌────────────┬──────────┬──────┬─────────────┬───────────┬────────────────────┬────────────────────┐
│ statistic  ┆ id       ┆ code ┆ name        ┆ continent ┆ wikipedia_link     ┆ keywords           │
│ ---        ┆ ---      ┆ ---  ┆ ---         ┆ ---       ┆ ---                ┆ ---                │
│ str        ┆ f64      ┆ str  ┆ str         ┆ str       ┆ str                ┆ str                │
╞════════════╪══════════╪══════╪═════════════╪═══════════╪════════════════════╪════════════════════╡
│ count      ┆ 247.0    ┆ 247  ┆ 247         ┆ 247       ┆ 247                ┆ 93                 │
│ null_count ┆ 0.0      ┆ 0    ┆ 0           ┆ 0         ┆ 0                  ┆ 154                │
│ mean       ┆ 302679.0 ┆ null ┆ null        ┆ null      ┆ null               ┆ null               │
│ std        ┆ 71.44695 ┆ null ┆ null        ┆ null      ┆ null               ┆ null               │
│ min        ┆ 302556.0 ┆ AD   ┆ Afghanistan ┆ AF        ┆ https://en.wikiped ┆ Aeroporti d'Italia │
│            ┆          ┆      ┆             ┆           ┆ ia.org/wiki/Af…    ┆                    │
│ 25%        ┆ 302618.0 ┆ null ┆ null        ┆ null      ┆ null               ┆ null               │
│ 50%        ┆ 302679.0 ┆ null ┆ null        ┆ null      ┆ null               ┆ null               │
│ 75%        ┆ 302741.0 ┆ null ┆ null        ┆ null      ┆ null               ┆ null               │
│ max        ┆ 302802.0 ┆ ZZ   ┆ Zimbabwe    ┆ SA        ┆ https://en.wikiped ┆ 한국의 공항        │
│            ┆          ┆      ┆             ┆           ┆ ia.org/wiki/Zi…    ┆                    │
└────────────┴──────────┴──────┴─────────────┴───────────┴────────────────────┴────────────────────┘

In [13]:
runways.describe()

shape: (9, 21)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ id        ┆ airport_r ┆ airport_i ┆ … ┆ he_longit ┆ he_elevat ┆ he_headin ┆ he_displ │
│ ---       ┆ ---       ┆ ef        ┆ dent      ┆   ┆ ude_deg   ┆ ion_ft    ┆ g_degT    ┆ aced_thr │
│ str       ┆ f64       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ eshold_f │
│           ┆           ┆ f64       ┆ str       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ t        │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 41811.0   ┆ 41811.0   ┆ 41811     ┆ … ┆ 14526.0   ┆ 12203.0   ┆ 16087.0   ┆ 3138.0   │
│ null_coun ┆ 0.0       ┆ 0.0       ┆ 0         ┆ … ┆ 27285.0   ┆ 29608.0   ┆ 25724.0   ┆ 38673.0  │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ 257669.41 ┆ 34968.662 ┆ null      ┆ … ┆ -40.06072 ┆ 1055.0394 ┆ 261.78785 ┆ 535.7313 │
│           ┆ 5608      ┆ 983       ┆           ┆   ┆           ┆ 17        ┆ 5         ┆ 58       │
│ std       ┆ 21970.279 ┆ 69876.061 ┆ null      ┆ … ┆ 79.824659 ┆ 1458.3885 ┆ 78.417155 ┆ 465.7251 │
│           ┆ 462       ┆ 079       ┆           ┆   ┆           ┆ 42        ┆           ┆ 47       │
│ min       ┆ 232758.0  ┆ 2.0       ┆ 00A       ┆ … ┆ -178.292  ┆ -1210.0   ┆ 0.0       ┆ 1.0      │
│ 25%       ┆ 243224.0  ┆ 8580.0    ┆ null      ┆ … ┆ -96.603   ┆ 116.0     ┆ 226.0     ┆ 228.0    │
│ 50%       ┆ 253682.0  ┆ 18751.0   ┆ null      ┆ … ┆ -80.2319  ┆ 564.0     ┆ 270.0     ┆ 400.0    │
│ 75%       ┆ 264151.0  ┆ 27543.0   ┆ null      ┆ … ┆ 15.5385   ┆ 1240.0    ┆ 316.0     ┆ 696.0    │
│ max       ┆ 342131.0  ┆ 342052.0  ┆ rjns      ┆ … ┆ 179.343   ┆ 13314.0   ┆ 363.0     ┆ 5001.0   │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [14]:
countries.select(
    pl.all().n_unique()
)

shape: (1, 6)
┌─────┬──────┬──────┬───────────┬────────────────┬──────────┐
│ id  ┆ code ┆ name ┆ continent ┆ wikipedia_link ┆ keywords │
│ --- ┆ ---  ┆ ---  ┆ ---       ┆ ---            ┆ ---      │
│ u32 ┆ u32  ┆ u32  ┆ u32       ┆ u32            ┆ u32      │
╞═════╪══════╪══════╪═══════════╪════════════════╪══════════╡
│ 247 ┆ 247  ┆ 247  ┆ 7         ┆ 247            ┆ 94       │
└─────┴──────┴──────┴───────────┴────────────────┴──────────┘

## Q1.1

In [16]:
countries_by_airports = countries.select(['code','name']).join(
    airports.group_by('iso_country').agg(
        pl.col('id').count().alias('airport_count')
    )    
    , how= 'left'
    , left_on =  'code'
    , right_on = 'iso_country'
).filter(~ ((pl.col('code') == 'ZZ') & pl.col('airport_count').is_null()) )\
.with_columns(
    pl.col("airport_count").fill_null(0)
)

In [17]:
top_filter = pl.col("airport_count").rank(method="min",descending=True) <=3
countries_by_airports_top3 = countries_by_airports.filter(top_filter).sort('airport_count', descending = True)

countries_by_airports_top3.write_csv('./results/q1_countries_by_airports_top3.csv')
countries_by_airports_top3

shape: (3, 3)
┌──────┬───────────────┬───────────────┐
│ code ┆ name          ┆ airport_count │
│ ---  ┆ ---           ┆ ---           │
│ str  ┆ str           ┆ u32           │
╞══════╪═══════════════╪═══════════════╡
│ US   ┆ United States ┆ 25170         │
│ BR   ┆ Brazil        ┆ 5546          │
│ CA   ┆ Canada        ┆ 2829          │
└──────┴───────────────┴───────────────┘

In [18]:
pl.Config.set_tbl_rows(-1)
bottom_filter =  pl.col("airport_count").rank(method="min",descending=False) <= 10
countries_by_airports_bottom10 = countries_by_airports.filter(bottom_filter).sort('airport_count', descending = True)
countries_by_airports_bottom10.write_csv('./results/q1_countries_by_airports_bottom10.csv')
countries_by_airports_bottom10

shape: (17, 3)
┌──────┬───────────────────────────────────┬───────────────┐
│ code ┆ name                              ┆ airport_count │
│ ---  ┆ ---                               ┆ ---           │
│ str  ┆ str                               ┆ u32           │
╞══════╪═══════════════════════════════════╪═══════════════╡
│ BL   ┆ Saint Barthélemy                  ┆ 1             │
│ CC   ┆ Cocos (Keeling) Islands           ┆ 1             │
│ CW   ┆ Curaçao                           ┆ 1             │
│ CX   ┆ Christmas Island                  ┆ 1             │
│ GI   ┆ Gibraltar                         ┆ 1             │
│ GM   ┆ Gambia                            ┆ 1             │
│ IO   ┆ British Indian Ocean Territory    ┆ 1             │
│ JE   ┆ Jersey                            ┆ 1             │
│ NF   ┆ Norfolk Island                    ┆ 1             │
│ NR   ┆ Nauru                             ┆ 1             │
│ NU   ┆ Niue                              ┆ 1             │
│ SX   ┆ Sint Maarten                      ┆ 1             │
│ VA   ┆ Vatican City                      ┆ 1             │
│ YT   ┆ Mayotte                           ┆ 1             │
│ GS   ┆ South Georgia and the South Sand… ┆ 0             │
│ PN   ┆ Pitcairn                          ┆ 0             │
│ TK   ┆ Tokelau                           ┆ 0             │
└──────┴───────────────────────────────────┴───────────────┘

## Q1.2

In [20]:
# fixed min -> ordinal to avoid duplicated airports
longest_runways_per_airport = runways.select(['airport_ref', 'length_ft', 'width_ft']).filter(
    pl.col("length_ft")
    .rank(method="ordinal", descending=True)
    .over("airport_ref") == 1
)

In [21]:
longest_runways_per_country=airports.select(['id','name','iso_country'])\
.join(
    longest_runways_per_airport
    , how = 'inner'
    , left_on = 'id'
    , right_on = 'airport_ref'
).filter(
    pl.col("length_ft")
    .rank(method="min", descending=True)
    .over("iso_country") == 1
).sort('length_ft', descending = True)

In [22]:
longest_runways_per_country.head()

shape: (5, 5)
┌───────┬─────────────────────────────────┬─────────────┬───────────┬──────────┐
│ id    ┆ name                            ┆ iso_country ┆ length_ft ┆ width_ft │
│ ---   ┆ ---                             ┆ ---         ┆ ---       ┆ ---      │
│ i64   ┆ str                             ┆ str         ┆ i64       ┆ i64      │
╞═══════╪═════════════════════════════════╪═════════════╪═══════════╪══════════╡
│ 46491 ┆ Pontiac Airpark Water Aerodrome ┆ CA          ┆ 120000    ┆ 1000     │
│ 22159 ┆ Gunflint Seaplane Base          ┆ US          ┆ 30000     ┆ 5000     │
│ 30788 ┆ Qamdo Bangda Airport            ┆ CN          ┆ 18045     ┆ 148      │
│ 26407 ┆ Ulyanovsk East Airport          ┆ RU          ┆ 16404     ┆ 323      │
│ 2847  ┆ Pierre Van Ryneveld Airport     ┆ ZA          ┆ 16076     ┆ 197      │
└───────┴─────────────────────────────────┴─────────────┴───────────┴──────────┘

In [23]:
longest_runways_per_country.write_csv('results/q1_longest_runways_per_country.csv')

# Q2

In [25]:
import requests as req
class api:
    def __init__(self, domain, timeout= (5,30)):
        self.domain = domain
        self.timeout = timeout
        self.session = req.Session()
    
    def _url(self, url_path):
        return self.domain + url_path
        
    def get(self, url_path, params = None, headers = None):
        url = self._url(url_path)
        print('***started***')
        print(f'''url : {url}''')
        try:
            res = self.session.get(url, params = params, headers = headers, timeout = self.timeout)
            # res.raise_for_status()
            
        except Exception as e:
            print(f"Type: {e.__class__.__name__}")
            print(f"Full: {type(e)}")
            print(f"Message: {str(e)}") 
            # raise
        else:
            print('successful')
        finally:            
            print(f'''***finished with staus code: {res.status_code}***''')
            print(f'''***finished with reason: {res.reason}***\n''')
            return res


    def put(self, url_path, data, params = None, headers = None):
        url = self._url(url_path)
        print('***started***')
        print(f'''url : {url}''')
        try:
            res = self.session.put(url, data = data , params = params, headers = headers, timeout = self.timeout)
            # res.raise_for_status()
            
        except Exception as e:
            print(f"Type: {e.__class__.__name__}")
            print(f"Full: {type(e)}")
            print(f"Message: {str(e)}") 
            # raise
        else:
            print('successful')
        finally:            
            print(f'''***finished with staus code: {res.status_code}***''')
            print(f'''***finished with reason: {res.reason}***\n''')
            return res

    def post(self, url_path, data = None, files = None, params = None, headers = None):
        url = self._url(url_path)
        print('***started***')
        print(f'''url : {url}''')
        try:
            res = self.session.post(url, data = data , params = params, headers = headers, timeout = self.timeout)
            # res.raise_for_status()
            
        except Exception as e:
            print(f"Type: {e.__class__.__name__}")
            print(f"Full: {type(e)}")
            print(f"Message: {str(e)}") 
            # raise
        else:
            print('successful')
        finally:            
            print(f'''***finished with staus code: {res.status_code}***''')
            print(f'''***finished with reason: {res.reason}***\n''')
            return res

In [26]:
from dotenv import load_dotenv
import os
load_dotenv()
print(os.getenv('shared_signature')[:30] + "...")

sv=2022-11-02&ss=b&srt=o&sp=wc...

In [27]:

date = '20260301'
initials = 'ms'
upload_info ={
    'account_name': 'sacodeassessment'
    , 'shared_signature': os.getenv('shared_signature')
    , 'blob_container' : 'results'
    , 'blob_path' : f'''ingest-assessment-{date}-{initials}'''
    , 'file':'results/q1_longest_runways_per_country.csv'
}

In [28]:
resp = api(f'''https://{upload_info['account_name']}.blob.core.windows.net''').put(
    url_path = (
        f'''/{upload_info['blob_container']}/{upload_info['blob_path']}'''
        f'''/{upload_info['file'].replace('results/q1_','')}'''
        f'''?{upload_info['shared_signature']}'''
    )
    , data = upload_info['file']
    , headers={'x-ms-blob-type': 'BlockBlob'}
)

***started***
url : https://sacodeassessment.blob.core.windows.net/results/ingest-assessment-20260301-ms/longest_runways_per_country.csv?sv=2022-11-02&ss=b&srt=o&sp=wc&se=2034-11-11T11:00:00Z&st=2024-11-10T23:00:00Z&spr=https&sig=D%2BgRbWPJDTmsbPtyfTEiTnb7gg594uNsvm62oQK49Yg%3D
successful
***finished with staus code: 201***
***finished with reason: Created***

In [29]:
azure_url = (
    f'''https://{upload_info['account_name']}.blob.core.windows.net'''
    f'''/{upload_info['blob_container']}/{upload_info['blob_path']}'''
    f'''/{upload_info['file'].replace('results/q1_','')}'''
    f'''?{upload_info['shared_signature']}'''
)
azure_url

'https://sacodeassessment.blob.core.windows.net/results/ingest-assessment-20260301-ms/longest_runways_per_country.csv?sv=2022-11-02&ss=b&srt=o&sp=wc&se=2034-11-11T11:00:00Z&st=2024-11-10T23:00:00Z&spr=https&sig=D%2BgRbWPJDTmsbPtyfTEiTnb7gg594uNsvm62oQK49Yg%3D'

In [30]:
# !curl -X PUT "{azure_url}" --data-binary @"{upload_info['file']}" -H "x-ms-blob-type: BlockBlob" -v

# Q3

In [32]:
import requests
import json
from pathlib import Path
import time

In [33]:
iso_countries = sorted(airports['iso_country'].unique().to_list())
iso_countries[:5]

['AD', 'AE', 'AF', 'AG', 'AI']

In [34]:

client_id=  'abc123'
host = 'code001.ecsbdp.com'
upload_path = f'{host}/revenues?client={client_id}'

In [35]:
for iso in ['us']:
    print(f'http://{host}/countries/{iso}')

http://code001.ecsbdp.com/countries/us

In [36]:
data = []
missing = []
exceptions = []

api_q3 = api(f'http://{host}', timeout=(1,5))

for iso in iso_countries:
    url_path = f'/countries/{iso}'
    resp = api_q3.get(url_path)
    if resp.status_code == 200:
        data.append({'iso': iso, 'resp': resp})
        print(f'added {iso} data')
    else:
        missing.append({'iso': iso, 'resp': resp})
        print(f'''couldn't find {iso} resp, with code {resp.status_code}''')
        
    time.sleep(0.1)

***started***
url : http://code001.ecsbdp.com/countries/AD
successful
***finished with staus code: 200***
***finished with reason: OK***

added AD data
***started***
url : http://code001.ecsbdp.com/countries/AE
successful
***finished with staus code: 200***
***finished with reason: OK***

added AE data
***started***
url : http://code001.ecsbdp.com/countries/AF
successful
***finished with staus code: 200***
***finished with reason: OK***

added AF data
***started***
url : http://code001.ecsbdp.com/countries/AG
successful
***finished with staus code: 200***
***finished with reason: OK***

added AG data
***started***
url : http://code001.ecsbdp.com/countries/AI
successful
***finished with staus code: 200***
***finished with reason: OK***

added AI data
***started***
url : http://code001.ecsbdp.com/countries/AL
successful
***finished with staus code: 200***
***finished with reason: OK***

added AL data
***started***
url : http://code001.ecsbdp.com/countries/AM
successful
***finished with staus code: 200***
***finished with reason: OK***

added AM data
***started***
url : http://code001.ecsbdp.com/countries/AO
successful
***finished with staus code: 200***
***finished with reason: OK***

added AO data
***started***
url : http://code001.ecsbdp.com/countries/AQ
successful
***finished with staus code: 200***
***finished with reason: OK***

added AQ data
***started***
url : http://code001.ecsbdp.com/countries/AR
successful
***finished with staus code: 200***
***finished with reason: OK***

added AR data
***started***
url : http://code001.ecsbdp.com/countries/AS
successful
***finished with staus code: 200***
***finished with reason: OK***

added AS data
***started***
url : http://code001.ecsbdp.com/countries/AT
successful
***finished with staus code: 200***
***finished with reason: OK***

added AT data
***started***
url : http://code001.ecsbdp.com/countries/AU
successful
***finished with staus code: 200***
***finished with reason: OK***

added AU data
***started***
url : http://code001.ecsbdp.com/countries/AW
successful
***finished with staus code: 200***
***finished with reason: OK***

added AW data
***started***
url : http://code001.ecsbdp.com/countries/AZ
successful
***finished with staus code: 200***
***finished with reason: OK***

added AZ data
***started***
url : http://code001.ecsbdp.com/countries/BA
successful
***finished with staus code: 200***
***finished with reason: OK***

added BA data
***started***
url : http://code001.ecsbdp.com/countries/BB
successful
***finished with staus code: 200***
***finished with reason: OK***

added BB data
***started***
url : http://code001.ecsbdp.com/countries/BD
successful
***finished with staus code: 200***
***finished with reason: OK***

added BD data
***started***
url : http://code001.ecsbdp.com/countries/BE
successful
***finished with staus code: 200***
***finished with reason: OK***

added BE data
***started***
url : http://code001.ecsbdp.com/countries/BF
successful
***finished with staus code: 200***
***finished with reason: OK***

added BF data
***started***
url : http://code001.ecsbdp.com/countries/BG
successful
***finished with staus code: 200***
***finished with reason: OK***

added BG data
***started***
url : http://code001.ecsbdp.com/countries/BH
successful
***finished with staus code: 200***
***finished with reason: OK***

added BH data
***started***
url : http://code001.ecsbdp.com/countries/BI
successful
***finished with staus code: 200***
***finished with reason: OK***

added BI data
***started***
url : http://code001.ecsbdp.com/countries/BJ
successful
***finished with staus code: 200***
***finished with reason: OK***

added BJ data
***started***
url : http://code001.ecsbdp.com/countries/BL
successful
***finished with staus code: 200***
***finished with reason: OK***

added BL data
***started***
url : http://code001.ecsbdp.com/countries/BM
successful
***finished with staus code: 200***
***finished with reason: OK***

added BM data
***started***
url : http://code001.ecsbdp.com/countries/BN
successful
***finished with staus code: 200***
***finished with reason: OK***

added BN data
***started***
url : http://code001.ecsbdp.com/countries/BO
successful
***finished with staus code: 200***
***finished with reason: OK***

added BO data
***started***
url : http://code001.ecsbdp.com/countries/BQ
successful
***finished with staus code: 200***
***finished with reason: OK***

added BQ data
***started***
url : http://code001.ecsbdp.com/countries/BR
successful
***finished with staus code: 200***
***finished with reason: OK***

added BR data
***started***
url : http://code001.ecsbdp.com/countries/BS
successful
***finished with staus code: 200***
***finished with reason: OK***

added BS data
***started***
url : http://code001.ecsbdp.com/countries/BT
successful
***finished with staus code: 200***
***finished with reason: OK***

added BT data
***started***
url : http://code001.ecsbdp.com/countries/BW
successful
***finished with staus code: 200***
***finished with reason: OK***

added BW data
***started***
url : http://code001.ecsbdp.com/countries/BY
successful
***finished with staus code: 200***
***finished with reason: OK***

added BY data
***started***
url : http://code001.ecsbdp.com/countries/BZ
successful
***finished with staus code: 200***
***finished with reason: OK***

added BZ data
***started***
url : http://code001.ecsbdp.com/countries/CA
successful
***finished with staus code: 200***
***finished with reason: OK***

added CA data
***started***
url : http://code001.ecsbdp.com/countries/CC
successful
***finished with staus code: 200***
***finished with reason: OK***

added CC data
***started***
url : http://code001.ecsbdp.com/countries/CD
successful
***finished with staus code: 200***
***finished with reason: OK***

added CD data
***started***
url : http://code001.ecsbdp.com/countries/CF
successful
***finished with staus code: 200***
***finished with reason: OK***

added CF data
***started***
url : http://code001.ecsbdp.com/countries/CG
successful
***finished with staus code: 200***
***finished with reason: OK***

added CG data
***started***
url : http://code001.ecsbdp.com/countries/CH
successful
***finished with staus code: 200***
***finished with reason: OK***

added CH data
***started***
url : http://code001.ecsbdp.com/countries/CI
successful
***finished with staus code: 404***
***finished with reason: Not Found***

couldn't find CI resp, with code 404
***started***
url : http://code001.ecsbdp.com/countries/CK
successful
***finished with staus code: 200***
***finished with reason: OK***

added CK data
***started***
url : http://code001.ecsbdp.com/countries/CL
successful
***finished with staus code: 200***
***finished with reason: OK***

added CL data
***started***
url : http://code001.ecsbdp.com/countries/CM
successful
***finished with staus code: 200***
***finished with reason: OK***

added CM data
***started***
url : http://code001.ecsbdp.com/countries/CN
successful
***finished with staus code: 200***
***finished with reason: OK***

added CN data
***started***
url : http://code001.ecsbdp.com/countries/CO
successful
***finished with staus code: 200***
***finished with reason: OK***

added CO data
***started***
url : http://code001.ecsbdp.com/countries/CR
successful
***finished with staus code: 200***
***finished with reason: OK***

added CR data
***started***
url : http://code001.ecsbdp.com/countries/CU
successful
***finished with staus code: 200***
***finished with reason: OK***

added CU data
***started***
url : http://code001.ecsbdp.com/countries/CV
successful
***finished with staus code: 200***
***finished with reason: OK***

added CV data
***started***
url : http://code001.ecsbdp.com/countries/CW
successful
***finished with staus code: 200***
***finished with reason: OK***

added CW data
***started***
url : http://code001.ecsbdp.com/countries/CX
successful
***finished with staus code: 200***
***finished with reason: OK***

added CX data
***started***
url : http://code001.ecsbdp.com/countries/CY
successful
***finished with staus code: 200***
***finished with reason: OK***

added CY data
***started***
url : http://code001.ecsbdp.com/countries/CZ
successful
***finished with staus code: 200***
***finished with reason: OK***

added CZ data
***started***
url : http://code001.ecsbdp.com/countries/DE
successful
***finished with staus code: 200***
***finished with reason: OK***

added DE data
***started***
url : http://code001.ecsbdp.com/countries/DJ
successful
***finished with staus code: 200***
***finished with reason: OK***

added DJ data
***started***
url : http://code001.ecsbdp.com/countries/DK
successful
***finished with staus code: 200***
***finished with reason: OK***

added DK data
***started***
url : http://code001.ecsbdp.com/countries/DM
successful
***finished with staus code: 200***
***finished with reason: OK***

added DM data
***started***
url : http://code001.ecsbdp.com/countries/DO
successful
***finished with staus code: 200***
***finished with reason: OK***

added DO data
***started***
url : http://code001.ecsbdp.com/countries/DZ
successful
***finished with staus code: 200***
***finished with reason: OK***

added DZ data
***started***
url : http://code001.ecsbdp.com/countries/EC
successful
***finished with staus code: 200***
***finished with reason: OK***

added EC data
***started***
url : http://code001.ecsbdp.com/countries/EE
successful
***finished with staus code: 200***
***finished with reason: OK***

added EE data
***started***
url : http://code001.ecsbdp.com/countries/EG
successful
***finished with staus code: 200***
***finished with reason: OK***

added EG data
***started***
url : http://code001.ecsbdp.com/countries/EH
successful
***finished with staus code: 200***
***finished with reason: OK***

added EH data
***started***
url : http://code001.ecsbdp.com/countries/ER
successful
***finished with staus code: 200***
***finished with reason: OK***

added ER data
***started***
url : http://code001.ecsbdp.com/countries/ES
successful
***finished with staus code: 200***
***finished with reason: OK***

added ES data
***started***
url : http://code001.ecsbdp.com/countries/ET
successful
***finished with staus code: 200***
***finished with reason: OK***

added ET data
***started***
url : http://code001.ecsbdp.com/countries/FI
successful
***finished with staus code: 200***
***finished with reason: OK***

added FI data
***started***
url : http://code001.ecsbdp.com/countries/FJ
successful
***finished with staus code: 200***
***finished with reason: OK***

added FJ data
***started***
url : http://code001.ecsbdp.com/countries/FK
successful
***finished with staus code: 200***
***finished with reason: OK***

added FK data
***started***
url : http://code001.ecsbdp.com/countries/FM
successful
***finished with staus code: 200***
***finished with reason: OK***

added FM data
***started***
url : http://code001.ecsbdp.com/countries/FO
successful
***finished with staus code: 200***
***finished with reason: OK***

added FO data
***started***
url : http://code001.ecsbdp.com/countries/FR
successful
***finished with staus code: 200***
***finished with reason: OK***

added FR data
***started***
url : http://code001.ecsbdp.com/countries/GA
successful
***finished with staus code: 200***
***finished with reason: OK***

added GA data
***started***
url : http://code001.ecsbdp.com/countries/GB
successful
***finished with staus code: 200***
***finished with reason: OK***

added GB data
***started***
url : http://code001.ecsbdp.com/countries/GD
successful
***finished with staus code: 200***
***finished with reason: OK***

added GD data
***started***
url : http://code001.ecsbdp.com/countries/GE
successful
***finished with staus code: 200***
***finished with reason: OK***

added GE data
***started***
url : http://code001.ecsbdp.com/countries/GF
successful
***finished with staus code: 200***
***finished with reason: OK***

added GF data
***started***
url : http://code001.ecsbdp.com/countries/GG
successful
***finished with staus code: 200***
***finished with reason: OK***

added GG data
***started***
url : http://code001.ecsbdp.com/countries/GH
successful
***finished with staus code: 200***
***finished with reason: OK***

added GH data
***started***
url : http://code001.ecsbdp.com/countries/GI
successful
***finished with staus code: 200***
***finished with reason: OK***

added GI data
***started***
url : http://code001.ecsbdp.com/countries/GL
successful
***finished with staus code: 200***
***finished with reason: OK***

added GL data
***started***
url : http://code001.ecsbdp.com/countries/GM
successful
***finished with staus code: 200***
***finished with reason: OK***

added GM data
***started***
url : http://code001.ecsbdp.com/countries/GN
successful
***finished with staus code: 200***
***finished with reason: OK***

added GN data
***started***
url : http://code001.ecsbdp.com/countries/GP
successful
***finished with staus code: 200***
***finished with reason: OK***

added GP data
***started***
url : http://code001.ecsbdp.com/countries/GQ
successful
***finished with staus code: 200***
***finished with reason: OK***

added GQ data
***started***
url : http://code001.ecsbdp.com/countries/GR
successful
***finished with staus code: 200***
***finished with reason: OK***

added GR data
***started***
url : http://code001.ecsbdp.com/countries/GT
successful
***finished with staus code: 200***
***finished with reason: OK***

added GT data
***started***
url : http://code001.ecsbdp.com/countries/GU
successful
***finished with staus code: 200***
***finished with reason: OK***

added GU data
***started***
url : http://code001.ecsbdp.com/countries/GW
successful
***finished with staus code: 200***
***finished with reason: OK***

added GW data
***started***
url : http://code001.ecsbdp.com/countries/GY
successful
***finished with staus code: 200***
***finished with reason: OK***

added GY data
***started***
url : http://code001.ecsbdp.com/countries/HK
successful
***finished with staus code: 200***
***finished with reason: OK***

added HK data
***started***
url : http://code001.ecsbdp.com/countries/HN
successful
***finished with staus code: 200***
***finished with reason: OK***

added HN data
***started***
url : http://code001.ecsbdp.com/countries/HR
successful
***finished with staus code: 200***
***finished with reason: OK***

added HR data
***started***
url : http://code001.ecsbdp.com/countries/HT
successful
***finished with staus code: 200***
***finished with reason: OK***

added HT data
***started***
url : http://code001.ecsbdp.com/countries/HU
successful
***finished with staus code: 200***
***finished with reason: OK***

added HU data
***started***
url : http://code001.ecsbdp.com/countries/ID
successful
***finished with staus code: 200***
***finished with reason: OK***

added ID data
***started***
url : http://code001.ecsbdp.com/countries/IE
successful
***finished with staus code: 200***
***finished with reason: OK***

added IE data
***started***
url : http://code001.ecsbdp.com/countries/IL
successful
***finished with staus code: 200***
***finished with reason: OK***

added IL data
***started***
url : http://code001.ecsbdp.com/countries/IM
successful
***finished with staus code: 200***
***finished with reason: OK***

added IM data
***started***
url : http://code001.ecsbdp.com/countries/IN
successful
***finished with staus code: 200***
***finished with reason: OK***

added IN data
***started***
url : http://code001.ecsbdp.com/countries/IO
successful
***finished with staus code: 200***
***finished with reason: OK***

added IO data
***started***
url : http://code001.ecsbdp.com/countries/IQ
successful
***finished with staus code: 200***
***finished with reason: OK***

added IQ data
***started***
url : http://code001.ecsbdp.com/countries/IR
successful
***finished with staus code: 200***
***finished with reason: OK***

added IR data
***started***
url : http://code001.ecsbdp.com/countries/IS
successful
***finished with staus code: 200***
***finished with reason: OK***

added IS data
***started***
url : http://code001.ecsbdp.com/countries/IT
successful
***finished with staus code: 200***
***finished with reason: OK***

added IT data
***started***
url : http://code001.ecsbdp.com/countries/JE
successful
***finished with staus code: 200***
***finished with reason: OK***

added JE data
***started***
url : http://code001.ecsbdp.com/countries/JM
successful
***finished with staus code: 200***
***finished with reason: OK***

added JM data
***started***
url : http://code001.ecsbdp.com/countries/JO
successful
***finished with staus code: 200***
***finished with reason: OK***

added JO data
***started***
url : http://code001.ecsbdp.com/countries/JP
successful
***finished with staus code: 200***
***finished with reason: OK***

added JP data
***started***
url : http://code001.ecsbdp.com/countries/KE
successful
***finished with staus code: 200***
***finished with reason: OK***

added KE data
***started***
url : http://code001.ecsbdp.com/countries/KG
successful
***finished with staus code: 200***
***finished with reason: OK***

added KG data
***started***
url : http://code001.ecsbdp.com/countries/KH
successful
***finished with staus code: 200***
***finished with reason: OK***

added KH data
***started***
url : http://code001.ecsbdp.com/countries/KI
successful
***finished with staus code: 200***
***finished with reason: OK***

added KI data
***started***
url : http://code001.ecsbdp.com/countries/KM
successful
***finished with staus code: 200***
***finished with reason: OK***

added KM data
***started***
url : http://code001.ecsbdp.com/countries/KN
successful
***finished with staus code: 200***
***finished with reason: OK***

added KN data
***started***
url : http://code001.ecsbdp.com/countries/KP
successful
***finished with staus code: 200***
***finished with reason: OK***

added KP data
***started***
url : http://code001.ecsbdp.com/countries/KR
successful
***finished with staus code: 200***
***finished with reason: OK***

added KR data
***started***
url : http://code001.ecsbdp.com/countries/KW
successful
***finished with staus code: 200***
***finished with reason: OK***

added KW data
***started***
url : http://code001.ecsbdp.com/countries/KY
successful
***finished with staus code: 200***
***finished with reason: OK***

added KY data
***started***
url : http://code001.ecsbdp.com/countries/KZ
successful
***finished with staus code: 200***
***finished with reason: OK***

added KZ data
***started***
url : http://code001.ecsbdp.com/countries/LA
successful
***finished with staus code: 200***
***finished with reason: OK***

added LA data
***started***
url : http://code001.ecsbdp.com/countries/LB
successful
***finished with staus code: 200***
***finished with reason: OK***

added LB data
***started***
url : http://code001.ecsbdp.com/countries/LC
successful
***finished with staus code: 200***
***finished with reason: OK***

added LC data
***started***
url : http://code001.ecsbdp.com/countries/LI
successful
***finished with staus code: 200***
***finished with reason: OK***

added LI data
***started***
url : http://code001.ecsbdp.com/countries/LK
successful
***finished with staus code: 200***
***finished with reason: OK***

added LK data
***started***
url : http://code001.ecsbdp.com/countries/LR
successful
***finished with staus code: 200***
***finished with reason: OK***

added LR data
***started***
url : http://code001.ecsbdp.com/countries/LS
successful
***finished with staus code: 200***
***finished with reason: OK***

added LS data
***started***
url : http://code001.ecsbdp.com/countries/LT
successful
***finished with staus code: 200***
***finished with reason: OK***

added LT data
***started***
url : http://code001.ecsbdp.com/countries/LU
successful
***finished with staus code: 200***
***finished with reason: OK***

added LU data
***started***
url : http://code001.ecsbdp.com/countries/LV
successful
***finished with staus code: 200***
***finished with reason: OK***

added LV data
***started***

In [37]:
# data = []
# missing = []
# exceptions = []

# for iso in iso_countries:
#     url = f'http://{host}/countries/{iso}'
#     print(f'url:{url}')
#     try:
#         resp = requests.get(url, timeout=(1,5))
#         if resp.status_code == 200:
#             data.append({'iso': iso, 'resp': resp})
#             print(f'added {iso} data')
#         else:
#             missing.append({'iso': iso, 'resp': resp})
#             print(f'''couldn't find {iso} resp, with code {resp.status_code}''')
#     except Exception as e:
#         exceptions.append({'iso': iso, 'exception': e})
#         print(f'{iso}: Unexpected {type(e).__name__}: {e}')
#     time.sleep(0.2)
#     print()

In [38]:
missing

[{'iso': 'CI', 'resp': <Response [404]>}]

In [39]:
{frozenset(x['resp'].json().keys()) for x in data}

{frozenset({'code', 'continent', 'name'}),
 frozenset({'code', 'continent', 'flag', 'name'})}

In [40]:
from collections import Counter

Counter(frozenset(x['resp'].json().keys()) for x in data)

Counter({frozenset({'code', 'continent', 'name'}): 241,
         frozenset({'code', 'continent', 'flag', 'name'}): 1})

In [41]:
countries_data = pl.DataFrame([x['resp'].json() for x in data])

In [42]:
countries_data.filter(~pl.col('flag').is_null())

shape: (1, 4)
┌──────┬────────────────┬───────────┬───────────────────────────────────┐
│ code ┆ name           ┆ continent ┆ flag                              │
│ ---  ┆ ---            ┆ ---       ┆ ---                               │
│ str  ┆ str            ┆ str       ┆ str                               │
╞══════╪════════════════╪═══════════╪═══════════════════════════════════╡
│ GB   ┆ United Kingdom ┆ EU        ┆ FLAG{d90ef201-1a5b-495a-ac90-44d… │
└──────┴────────────────┴───────────┴───────────────────────────────────┘

In [43]:
countries_data.write_csv('logs/q3_countries_data.csv')

In [44]:
with open('revenues.txt', 'w') as f:
    pass

In [45]:
api_q3 = api(f'http://{host}', timeout=(1,5))
api_q3.post(f'/revenues?client={client_id}', files={'file': open('revenues.txt', 'rb')} )

***started***
url : http://code001.ecsbdp.com/revenues?client=abc123
successful
***finished with staus code: 201***
***finished with reason: Created***

In [46]:
# revenues_url = f'http://{host}/revenues?client={client_id}'

# requests.post(revenues_url, files={'file': open('revenues.txt', 'rb')})

# Q4

In [48]:
import psycopg2

In [49]:
conn = psycopg2.connect(host="code001.ecsbdp.com", port=5432, dbname="chinook", user="larry", password="iddqd")

In [50]:
tables = pl.read_database("SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' ORDER BY table_name;", conn)
tables

shape: (11, 1)
┌────────────────┐
│ table_name     │
│ ---            │
│ str            │
╞════════════════╡
│ album          │
│ artist         │
│ customer       │
│ employee       │
│ genre          │
│ invoice        │
│ invoice_line   │
│ media_type     │
│ playlist       │
│ playlist_track │
│ track          │
└────────────────┘

In [51]:
desc = pl.read_database("""
  SELECT table_name, column_name, data_type, is_nullable
  FROM information_schema.columns 
  WHERE table_schema = 'public' 
  ORDER BY table_name, ordinal_position
""", conn)
desc.head()

shape: (5, 4)
┌────────────┬─────────────┬───────────────────┬─────────────┐
│ table_name ┆ column_name ┆ data_type         ┆ is_nullable │
│ ---        ┆ ---         ┆ ---               ┆ ---         │
│ str        ┆ str         ┆ str               ┆ str         │
╞════════════╪═════════════╪═══════════════════╪═════════════╡
│ album      ┆ album_id    ┆ integer           ┆ NO          │
│ album      ┆ title       ┆ character varying ┆ NO          │
│ album      ┆ artist_id   ┆ integer           ┆ NO          │
│ artist     ┆ artist_id   ┆ integer           ┆ NO          │
│ artist     ┆ name        ┆ character varying ┆ YES         │
└────────────┴─────────────┴───────────────────┴─────────────┘

In [52]:
# related tables and columns
# │ invoice        ┆ customer_id         ┆ integer                     ┆ NO          │
# │ invoice        ┆ total               ┆ numeric                     ┆ NO          │
# │ invoice_line   ┆ track_id            ┆ integer                     ┆ NO          │
# │ track          ┆ track_id            ┆ integer                     ┆ NO          │
# │ track          ┆ genre_id            ┆ integer                     ┆ YES         │
# | genre          ┆ genre_id            ┆ integer                     ┆ NO          │
# │ genre          ┆ name                ┆ character varying           ┆ YES

In [53]:

conn = psycopg2.connect(host="code001.ecsbdp.com", port=5432, dbname="chinook", user="larry", password="iddqd")
jazz_hypothesis = pl.read_database(
    """
    WITH track_type AS (
        SELECT
            track_id
            , CASE WHEN g.name = 'Jazz' THEN 1 ELSE 0 END AS is_jazz
        FROM track AS t
        LEFT JOIN genre AS g USING (genre_id)
    )
    , customer_sales_by_type AS (
        SELECT
            customer_id
            , MAX(is_jazz) AS is_jazz_customer
            , SUM(total) total_sales
        FROM invoice AS i
        LEFT JOIN invoice_line AS il USING(invoice_id)
        LEFT JOIN track_type AS tt USING(track_id)
        GROUP BY customer_id
    )
    SELECT 
        is_jazz_customer
        , SUM(total_sales) AS total_sales
    FROM customer_sales_by_type
    GROUP BY is_jazz_customer
    """
    , conn
)

In [54]:
jazz_hypothesis

shape: (2, 2)
┌──────────────────┬──────────────┐
│ is_jazz_customer ┆ total_sales  │
│ ---              ┆ ---          │
│ i64              ┆ decimal[*,2] │
╞══════════════════╪══════════════╡
│ 0                ┆ 9762.74      │
│ 1                ┆ 11085.88     │
└──────────────────┴──────────────┘

In [55]:
jazz_hypothesis = jazz_hypothesis.with_columns([
    pl.col(pl.Decimal).cast(pl.Float64)
])

In [56]:
jazz_hypothesis.write_csv('results/q4_jazz_hypothesis.csv')

In [57]:
pl.read_database(
    """
    SELECT album.title
    FROM track
    JOIN album ON (track.album_id = album.album_id)
    WHERE LOWER(track.name) = LOWER('Enter Sandman')
    """
    , conn
)

shape: (2, 1)
┌────────────────────────────────┐
│ title                          │
│ ---                            │
│ str                            │
╞════════════════════════════════╡
│ Plays Metallica By Four Cellos │
│ Black Album                    │
└────────────────────────────────┘

In [58]:
indexes = pl.read_database("""
    SELECT schemaname, tablename, indexname, indexdef 
    FROM pg_indexes 
    WHERE schemaname = 'public' 
    ORDER BY tablename, indexname;
""", conn)
with pl.Config(
    fmt_str_lengths=200, 
    tbl_rows=-1, 
    tbl_cols=-1
    ):
    print(indexes)

shape: (30, 4)
┌────────────┬────────────────┬─────────────────────────────┬──────────────────────────────────────┐
│ schemaname ┆ tablename      ┆ indexname                   ┆ indexdef                             │
│ ---        ┆ ---            ┆ ---                         ┆ ---                                  │
│ str        ┆ str            ┆ str                         ┆ str                                  │
╞════════════╪════════════════╪═════════════════════════════╪══════════════════════════════════════╡
│ public     ┆ actor          ┆ actor_pkey                  ┆ CREATE UNIQUE INDEX actor_pkey ON    │
│            ┆                ┆                             ┆ public.actor USING btree (actor_id)  │
│ public     ┆ actor          ┆ idx_actor_last_name         ┆ CREATE INDEX idx_actor_last_name ON  │
│            ┆                ┆                             ┆ public.actor USING btree (last_name) │
│ public     ┆ album          ┆ ifk_album_artist_id         ┆ CREATE INDEX ifk_album_artist_id ON  │
│            ┆                ┆                             ┆ public.album USING btree (artist_id) │
│ public     ┆ album          ┆ pk_album                    ┆ CREATE UNIQUE INDEX pk_album ON      │
│            ┆                ┆                             ┆ public.album USING btree (album_id)  │
│ public     ┆ artist         ┆ pk_artist                   ┆ CREATE UNIQUE INDEX pk_artist ON     │
│            ┆                ┆                             ┆ public.artist USING btree            │
│            ┆                ┆                             ┆ (artist_id)                          │
│ public     ┆ category       ┆ category_pkey               ┆ CREATE UNIQUE INDEX category_pkey ON │
│            ┆                ┆                             ┆ public.category USING btree          │
│            ┆                ┆                             ┆ (category_id)                        │
│ public     ┆ customer       ┆ ifk_customer_support_rep_id ┆ CREATE INDEX                         │
│            ┆                ┆                             ┆ ifk_customer_support_rep_id ON       │
│            ┆                ┆                             ┆ public.customer USING btree          │
│            ┆                ┆                             ┆ (support_rep_id)                     │
│ public     ┆ customer       ┆ pk_customer                 ┆ CREATE UNIQUE INDEX pk_customer ON   │
│            ┆                ┆                             ┆ public.customer USING btree          │
│            ┆                ┆                             ┆ (customer_id)                        │
│ public     ┆ employee       ┆ ifk_employee_reports_to     ┆ CREATE INDEX ifk_employee_reports_to │
│            ┆                ┆                             ┆ ON public.employee USING btree       │
│            ┆                ┆                             ┆ (reports_to)                         │
│ public     ┆ employee       ┆ pk_employee                 ┆ CREATE UNIQUE INDEX pk_employee ON   │
│            ┆                ┆                             ┆ public.employee USING btree          │
│            ┆                ┆                             ┆ (employee_id)                        │
│ public     ┆ film           ┆ film_fulltext_idx           ┆ CREATE INDEX film_fulltext_idx ON    │
│            ┆                ┆                             ┆ public.film USING gist (fulltext)    │
│ public     ┆ film           ┆ film_pkey                   ┆ CREATE UNIQUE INDEX film_pkey ON     │
│            ┆                ┆                             ┆ public.film USING btree (film_id)    │
│ public     ┆ film           ┆ idx_fk_language_id          ┆ CREATE INDEX idx_fk_language_id ON   │
│            ┆                ┆                             ┆ public.film USING btree              │
│            ┆                ┆                             ┆ (language_id)                        │
│ public     ┆ film           ┆ idx_title                   ┆ CREATE INDEX idx_title ON            │
│            ┆                ┆                             ┆ public.film USING btree (title)      │
│ public     ┆ film_actor     ┆ film_actor_pkey             ┆ CREATE UNIQUE INDEX film_actor_pkey  │
│            ┆                ┆                             ┆ ON public.film_actor USING btree     │
│            ┆                ┆                             ┆ (actor_id, film_id)                  │
│ public     ┆ film_actor     ┆ idx_fk_film_id              ┆ CREATE INDEX idx_fk_film_id ON       │
│            ┆                ┆                             ┆ public.film_actor USING btree        │
│            ┆                ┆                             ┆ (film_id)                            │
│ public     ┆ genre          ┆ pk_genre                    ┆ CREATE UNIQUE INDEX pk_genre ON      │
│            ┆                ┆                             ┆ public.genre USING btree (genre_id)  │
│ public     ┆ invoice        ┆ ifk_invoice_customer_id     ┆ CREATE INDEX ifk_invoice_customer_id │
│            ┆                ┆                             ┆ ON public.invoice USING btree        │
│            ┆                ┆                             ┆ (customer_id)                        │
│ public     ┆ invoice        ┆ pk_invoice                  ┆ CREATE UNIQUE INDEX pk_invoice ON    │
│            ┆                ┆                             ┆ public.invoice USING btree           │
│            ┆                ┆                             ┆ (invoice_id)                         │
│ public     ┆ invoice_line   ┆ ifk_invoice_line_invoice_id ┆ CREATE INDEX                         │
│            ┆                ┆                             ┆ ifk_invoice_line_invoice_id ON       │
│            ┆                ┆                             ┆ public.invoice_line USING btree      │
│            ┆                ┆                             ┆ (invoice_id)                         │
│ public     ┆ invoice_line   ┆ ifk_invoice_line_track_id   ┆ CREATE INDEX                         │
│            ┆                ┆                             ┆ ifk_invoice_line_track_id ON         │
│            ┆                ┆                             ┆ public.invoice_line USING btree      │
│            ┆                ┆                             ┆ (track_id)                           │
│ public     ┆ invoice_line   ┆ ok_invoice_line             ┆ CREATE UNIQUE INDEX ok_invoice_line  │
│            ┆                ┆                             ┆ ON public.invoice_line USING btree   │
│            ┆                ┆                             ┆ (invoice_line_id)                    │
│ public     ┆ media_type     ┆ pk_media_type               ┆ CREATE UNIQUE INDEX pk_media_type ON │
│            ┆                ┆                             ┆ public.media_type USING btree        │
│            ┆                ┆                             ┆ (media_type_id)                      │
│ public     ┆ playlist       ┆ pk_playlist                 ┆ CREATE UNIQUE INDEX pk_playlist ON   │
│            ┆                ┆                             ┆ public.playlist USING btree          │
│            ┆                ┆                             ┆ (playlist_id)                        │
│ public     ┆ playlist_track ┆ ifk_playlist_track_track_id ┆ CREATE INDEX                         │
│            ┆                ┆                             ┆ ifk_playlist_track_track_id ON       │
│            ┆                ┆                             ┆ public.playlist_track USING btree    │
│            ┆                ┆                             ┆ (track_id)                           │
│ public     ┆ playlist_track ┆ pk_playlist_track           ┆ CREATE UNIQUE INDEX                  │
│            ┆                ┆                             ┆ pk_playlist_track ON                 │
│            ┆                ┆                             ┆ public.playlist_track USING btree    │
│            ┆                ┆                             ┆ (playlist_id, track_id)              │
│ public     ┆ track          ┆ ifk_track_album_id          ┆ CREATE INDEX ifk_track_album_id ON   │
│            ┆                ┆                             ┆ public.track USING btree (album_id)  │
│ public     ┆ track          ┆ ifk_track_genre_id          ┆ CREATE INDEX ifk_track_genre_id ON   │
│            ┆                ┆                             ┆ public.track USING btree (genre_id)  │
│ public     ┆ track          ┆ ifk_track_media_type_id     ┆ CREATE INDEX ifk_track_media_type_id │
│            ┆                ┆                             ┆ ON public.track USING btree          │
│            ┆                ┆                             ┆ (media_type_id)                      │
│ public     ┆ track          ┆ pk_track                    ┆ CREATE UNIQUE INDEX pk_track ON      │
│            ┆                ┆                             ┆ public.track USING btree (track_id)  │
└────────────┴────────────────┴─────────────────────────────┴──────────────────────────────────────┘

In [59]:
""""
More explanation in Google Doc
Solution 2: Indexing (normal)
CREATE INDEX idx_track_name_lower ON track (LOWER(name));
Solution 2: Trigram
CREATE INDEX idx_track_name_trgm ON track USING GIN (name gin_trgm_ops);
"""

'"\nMore explanation in Google Doc\nSolution 2: Indexing (normal)\nCREATE INDEX idx_track_name_lower ON track (LOWER(name));\nSolution 2: Trigram\nCREATE INDEX idx_track_name_trgm ON track USING GIN (name gin_trgm_ops);\n'

# Q5

In [61]:
import base64
import json
import jwt
from datetime import datetime

token = "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Im5PbzNaRHJPRFhFSzFqS1doWHNsSFJfS1hFZ\
yIsImtpZCI6Im5PbzNaRHJPRFhFSzFqS1doWHNsSFJfS1hFZyJ9.eyJhdWQiOiJodHRwczovL0VuZWNvLm\
9ubWljcm9zb2Z0LmNvbS9lY3Nhei1hcGlnZWUtb2RwLXQiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dz\
Lm5ldC9lY2EzNjA1NC00OWE5LTQ3MzEtYTQyZi04NDAwNjcwZmMwMjIvIiwiaWF0IjoxNjE2NDE2NzA1LC\
JuYmYiOjE2MTY0MTY3MDUsImV4cCI6MTYxNjQyMDYwNSwiYWlvIjoiRTJaZ1lFZzNWZG1mNmhzcHYvdVBN\
YmZmOC9NQ0FBPT0iLCJhcHBpZCI6IjFlMGZiMzU0LWE3OGQtNGY1Yi05OTY2LWVkNjIzYTYyNDU5OSIsI\
mlkcCI6Imh0dHBzOi8vc3RzLndpbmRvd3MubmV0L2VjYTM2MDU0LTQ5YTktNDczMS1hNDJmLTg0MDA2NzB\
mYzAyMi8iLCJvaWQiOiJkYjZlODlmOS1kYjE2LTQyNTItOTQyOS1jNGQ1ZTQ4YWRhYmQiLCJzdWIiOiJk\
YjZlODlmOS1kYjE2LTQyNTItOTQyOS1jNGQ1ZTQ4YWRhYmQiLCJ0aWQiOiJlY2EzNjA1NC00OWE5LTQ3M\
zEtYTQyZi04NDAwNjcwZmMwMjIiLCJ1dGkiOiJTZ0JhN1EzS1RVeTNRZjhoek9ZM0FBIiwidmVyIjoiMS\
4wIn0.AZRHBIxtI9uOT99Q0WRII1wPLKbrcBU-BHmQfUvaCCAnKApOZyrH3kxxtYjejgDTnoPIS0I1NnH0p\
xNd2ATN50fcHjsXkCr3DaspJggLSp2rT2nBMkTDyPBKIzw6rZ9tRrwsuFVXh2cYP1kIgoX-PxpWfzIsyXc\
tcSzbgYnLOJpiVDiZuzhi4YWbmvclO5iezLLpXvQ0ER034tco9An6LtAGH0mK0-4FHW4McQGLpWPXhwAVL\
RzNdCXx4TNnOK7eDAVyvxffDlbG9OSmd-PnLbFJKHwWNan06D7hTC8yQa4k-k0gcnHjDYKirG7CfnR5b6d\
KSst-BCa3X9w"

header, payload, signature = token.split('.')

header_json = base64.urlsafe_b64decode(header + '==').decode()
payload_json = base64.urlsafe_b64decode(payload + '==').decode()

header_decoded = json.loads(header_json)
payload_decoded = json.loads(payload_json)

print("=== HEADER ===")
print(header_decoded)
print("\n=== PAYLOAD ===")
print(payload_decoded)

exp_unix = payload_decoded['exp']
exp_date = datetime.fromtimestamp(exp_unix).strftime('%Y-%m-%d %H:%M UTC')
print(f"Expiry: {exp_date}")

print(f"Issuer: {payload_decoded['iss']}")
print(f"Audience: {payload_decoded['aud']}")
print(f"App ID: {payload_decoded['appid']}")
# print(f"Roles: {payload_decoded['roles']}")

decoded = jwt.decode(token, options={"verify_signature": False})
print("\n=== FULL DECODE ===")
print(decoded)

=== HEADER ===
{'typ': 'JWT', 'alg': 'RS256', 'x5t': 'nOo3ZDrODXEK1jKWhXslHR_KXEg', 'kid': 'nOo3ZDrODXEK1jKWhXslHR_KXEg'}

=== PAYLOAD ===
{'aud': 'https://Eneco.onmicrosoft.com/ecsaz-apigee-odp-t', 'iss': 'https://sts.windows.net/eca36054-49a9-4731-a42f-8400670fc022/', 'iat': 1616416705, 'nbf': 1616416705, 'exp': 1616420605, 'aio': 'E2ZgYEg3Vdmf6hspv/uPMbff8/MCAA==', 'appid': '1e0fb354-a78d-4f5b-9966-ed623a624599', 'idp': 'https://sts.windows.net/eca36054-49a9-4731-a42f-8400670fc022/', 'oid': 'db6e89f9-db16-4252-9429-c4d5e48adabd', 'sub': 'db6e89f9-db16-4252-9429-c4d5e48adabd', 'tid': 'eca36054-49a9-4731-a42f-8400670fc022', 'uti': 'SgBa7Q3KTUy3Qf8hzOY3AA', 'ver': '1.0'}
Expiry: 2021-03-22 14:43 UTC
Issuer: https://sts.windows.net/eca36054-49a9-4731-a42f-8400670fc022/
Audience: https://Eneco.onmicrosoft.com/ecsaz-apigee-odp-t
App ID: 1e0fb354-a78d-4f5b-9966-ed623a624599

=== FULL DECODE ===
{'aud': 'https://Eneco.onmicrosoft.com/ecsaz-apigee-odp-t', 'iss': 'https://sts.windows.net/eca36054-49a9-4731-a42f-8400670fc022/', 'iat': 1616416705, 'nbf': 1616416705, 'exp': 1616420605, 'aio': 'E2ZgYEg3Vdmf6hspv/uPMbff8/MCAA==', 'appid': '1e0fb354-a78d-4f5b-9966-ed623a624599', 'idp': 'https://sts.windows.net/eca36054-49a9-4731-a42f-8400670fc022/', 'oid': 'db6e89f9-db16-4252-9429-c4d5e48adabd', 'sub': 'db6e89f9-db16-4252-9429-c4d5e48adabd', 'tid': 'eca36054-49a9-4731-a42f-8400670fc022', 'uti': 'SgBa7Q3KTUy3Qf8hzOY3AA', 'ver': '1.0'}

In [62]:
with open("results/q5_reponse_decoded.json", "w") as f:
    json.dump(decoded, f, indent=4)

# Q6

In [64]:
!echo "RkxBR3s3Mjc0ZTVkYy1hYjYwLTRmYzItOGY1MS1lZTZlY2ViNmJlZjd9" | base64 -d

FLAG{7274e5dc-ab60-4fc2-8f51-ee6eceb6bef7}

In [65]:
urls_str = ' '.join(urls.values())
urls_str

'https://sacodeassessment.blob.core.windows.net/public/airports.csv https://sacodeassessment.blob.core.windows.net/public/countries.csv https://sacodeassessment.blob.core.windows.net/public/runways.csv'

In [66]:
countries.filter(
    pl.max_horizontal(pl.col(pl.String).str.to_lowercase().str.contains('flag\{'))
    | pl.max_horizontal(pl.col(pl.String).str.to_lowercase().str.contains('RkxBR3s'))
)

shape: (1, 6)
┌────────┬──────┬────────┬───────────┬──────────────────────────────┬──────────────────────────────┐
│ id     ┆ code ┆ name   ┆ continent ┆ wikipedia_link               ┆ keywords                     │
│ ---    ┆ ---  ┆ ---    ┆ ---       ┆ ---                          ┆ ---                          │
│ i64    ┆ str  ┆ str    ┆ str       ┆ str                          ┆ str                          │
╞════════╪══════╪════════╪═══════════╪══════════════════════════════╪══════════════════════════════╡
│ 302629 ┆ CY   ┆ Cyprus ┆ AS        ┆ https://en.wikipedia.org/wik ┆ FLAG{e9cade1a-55a8-4af5-887d │
│        ┆      ┆        ┆           ┆ i/Cy…                        ┆ -a70…                        │
└────────┴──────┴────────┴───────────┴──────────────────────────────┴──────────────────────────────┘

In [67]:
airports.filter(
    pl.max_horizontal(pl.col(pl.String).str.to_lowercase().str.contains('flag\{'))
    | pl.max_horizontal(pl.col(pl.String).str.to_lowercase().str.contains('RkxBR3s'))
)

shape: (0, 18)
┌─────┬───────┬──────┬──────┬───┬────────────┬───────────┬────────────────┬──────────┐
│ id  ┆ ident ┆ type ┆ name ┆ … ┆ local_code ┆ home_link ┆ wikipedia_link ┆ keywords │
│ --- ┆ ---   ┆ ---  ┆ ---  ┆   ┆ ---        ┆ ---       ┆ ---            ┆ ---      │
│ i64 ┆ str   ┆ str  ┆ str  ┆   ┆ str        ┆ str       ┆ str            ┆ str      │
╞═════╪═══════╪══════╪══════╪═══╪════════════╪═══════════╪════════════════╪══════════╡
└─────┴───────┴──────┴──────┴───┴────────────┴───────────┴────────────────┴──────────┘

In [68]:
runways.filter(
    pl.max_horizontal(pl.col(pl.String).str.to_lowercase().str.contains('flag\{'))
    | pl.max_horizontal(pl.col(pl.String).str.to_lowercase().str.contains('RkxBR3s'))
)

shape: (0, 20)
┌─────┬────────────┬────────────┬───────────┬───┬────────────┬────────────┬────────────┬───────────┐
│ id  ┆ airport_re ┆ airport_id ┆ length_ft ┆ … ┆ he_longitu ┆ he_elevati ┆ he_heading ┆ he_displa │
│ --- ┆ f          ┆ ent        ┆ ---       ┆   ┆ de_deg     ┆ on_ft      ┆ _degT      ┆ ced_thres │
│ i64 ┆ ---        ┆ ---        ┆ i64       ┆   ┆ ---        ┆ ---        ┆ ---        ┆ hold_ft   │
│     ┆ i64        ┆ str        ┆           ┆   ┆ f64        ┆ i64        ┆ f64        ┆ ---       │
│     ┆            ┆            ┆           ┆   ┆            ┆            ┆            ┆ i64       │
╞═════╪════════════╪════════════╪═══════════╪═══╪════════════╪════════════╪════════════╪═══════════╡
└─────┴────────────┴────────────┴───────────┴───┴────────────┴────────────┴────────────┴───────────┘

In [69]:
# %%bash -s "$urls_str"
# mkdir -p logs
# cd logs
# read -a urls <<< "$1"
# for url in "${urls[@]}"; do
#   fn=$(basename "$url")
#   curl -O "$url" && echo "✅ $fn"
#   echo "=== $fn flags ==="
#   grep -i 'FLAG{' "$fn"
#   grep 'RkxBR3s' "$fn"
#   echo "---"
# done

In [70]:
countries_data.filter(~pl.col('flag').is_null())

shape: (1, 4)
┌──────┬────────────────┬───────────┬───────────────────────────────────┐
│ code ┆ name           ┆ continent ┆ flag                              │
│ ---  ┆ ---            ┆ ---       ┆ ---                               │
│ str  ┆ str            ┆ str       ┆ str                               │
╞══════╪════════════════╪═══════════╪═══════════════════════════════════╡
│ GB   ┆ United Kingdom ┆ EU        ┆ FLAG{d90ef201-1a5b-495a-ac90-44d… │
└──────┴────────────────┴───────────┴───────────────────────────────────┘

In [71]:
for table_name, column_name, data_type, is_nullable in desc.iter_rows():
    if data_type == 'character varying':
        
        flags = pl.read_database(f"""
          SELECT {column_name}
          FROM {table_name} 
          WHERE lower({column_name}) ILIKE '%flag%' OR lower({column_name}) ILIKE '%rkxbr3s'
        """, conn)
        if len(flags)>0:
            print(table_name, column_name)
            print(flags)

track name
shape: (1, 1)
┌───────────────────────────────────┐
│ name                              │
│ ---                               │
│ str                               │
╞═══════════════════════════════════╡
│ The Four Horsemen FLAG{e9613d97-… │
└───────────────────────────────────┘

In [72]:
full_desc = pl.read_database("""
  SELECT *
  FROM information_schema.columns 
""", conn)

In [73]:
for col in full_desc.columns:
    flags = pl.read_database(f"""
      SELECT {col}
      FROM information_schema.columns 
      WHERE lower({col}::text) ILIKE '%flag%' OR lower({col}::text) ILIKE '%rkxbr3s'
    """, conn)
    if len(flags)>0:
        print(col)
        print(flags)